name: LightHouse CI
on:
  push:
    branches:
      - Fix-#404-lighthouse-ci-implement
jobs:
  lighthouseci:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node environment (14.x)
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install  npm packages
      - run: npm install
      - name: Image resize
        run: npm run resize-images
      - name: Project build
        run: npm run build
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.7.x
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}