name: Percy snapshots
on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev
      - Fix-#404-lighthouse-ci-implement
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup node environment (14.x)
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install  npm packages
        run: npm install
      - name: Image resize
        run: npm run resize-images
      - name: Project build
        run: npm run build
      # - name: Percy Snapshots
      #   uses: percy/exec-action@v0.3.1
      #   with:
      #     command: "node snapshots.js"
      #   env:
      #     PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  percy:
    needs: build
    steps:
      - name: Percy Snapshots
        uses: percy/exec-action@v0.3.1
        with:
          command: "node snapshots.js"
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  lhci:
    needs: build
    steps:
      - name: install lighthouse global
        run: npm install -g @lhci/cli@0.7.x
      - name: lighthouse run
        run: lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}

        